project_id = "dpeljwqtkjjkriobkhtj"

[functions.encrypt-api-key]
verify_jwt = true

[functions.chat-proxy]
verify_jwt = true

[functions.polar-webhook]
verify_jwt = false

[functions.create-polar-checkout]
verify_jwt = true

[functions.polar-customer-portal]
verify_jwt = true
